# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorial',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_templates', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to='problems.company'),
        ),
        migrations.AddField(
            model_name='problemcompany',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_companies', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.ManyToManyField(related_name='problems', through='problems.ProblemCompany', to='problems.company'),
        ),
        migrations.AddField(
            model_name='problemhint',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemlistitem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_appearances', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemlistitem',
            name='problem_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='problems.problemlist'),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemtag',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tags', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_problems', to='problems.tag'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', through='problems.ProblemTag', to='problems.tag'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together={('problem', 'language')},
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user'], name='problems_bo_user_id_d6c558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='problemcompany',
            unique_together={('problem', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='problemhint',
            unique_together={('problem', 'order_num')},
        ),
        migrations.AddIndex(
            model_name='problemlist',
            index=models.Index(fields=['user', 'is_public'], name='problems_pr_user_id_f35a6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problemlistitem',
            unique_together={('problem_list', 'order_num'), ('problem_list', 'problem')},
        ),
        migrations.AddIndex(
            model_name='problemreport',
            index=models.Index(fields=['status'], name='problems_pr_status_2eef40_idx'),
        ),
        migrations.AddIndex(
            model_name='problemreport',
            index=models.Index(fields=['problem', 'status'], name='problems_pr_problem_fe1f29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problemtag',
            unique_together={('problem', 'tag')},
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty', 'is_active'], name='problems_pr_difficu_ba7ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_premium', 'is_active'], name='problems_pr_is_prem_9a9e90_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['order_num'], name='problems_pr_order_n_d675c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'order_num')},
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['user'], name='problems_us_user_id_fd46f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'problem')},
        ),
    ]
