# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Study Plan Progress',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], db_index=True, default='mixed', max_length=20)),
                ('total_days', models.PositiveSmallIntegerField(default=30, help_text='Total number of days in the plan. Must match the max day_num in StudyPlanItem.')),
                ('total_problems', models.PositiveSmallIntegerField(default=0, help_text='Denormalised count of all problems across all days. Updated on item save/delete.')),
                ('cover_image_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(db_index=True, default=False, help_text='If True, only premium users can enrol.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive plans are hidden from the catalogue but existing enrolments are unaffected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Plan',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_active', 'is_premium'], name='study_plans_is_acti_d4aba9_idx'), models.Index(fields=['difficulty', 'is_active'], name='study_plans_difficu_e0bc84_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.PositiveSmallIntegerField(help_text='Which day of the plan this problem belongs to (1-indexed).')),
                ('order_num', models.PositiveSmallIntegerField(help_text='Display order within the day (1 = first problem of the day).')),
                ('note', models.TextField(blank=True, help_text='Optional editorial note shown alongside the problem on this day.')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='problems.problem')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='study_plans.studyplan')),
            ],
            options={
                'verbose_name': 'Study Plan Item',
                'ordering': ['day_num', 'order_num'],
            },
        ),
        migrations.CreateModel(
            name='UserStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.PositiveSmallIntegerField(default=1, help_text='The day the user is currently working on.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set by signal when all items across all days are marked complete.', null=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='study_plans.studyplan')),
            ],
            options={
                'verbose_name': 'User Study Plan Enrolment',
            },
        ),
    ]
