# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_plans', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_enrolments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstudyplanprogress',
            name='study_plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='study_plans.studyplanitem'),
        ),
        migrations.AddField(
            model_name='userstudyplanprogress',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='The accepted submission that completed this item. Null if marked manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_completions', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='userstudyplanprogress',
            name='user_study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='study_plans.userstudyplan'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['study_plan', 'day_num'], name='study_plans_study_p_bb8dea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studyplanitem',
            unique_together={('study_plan', 'day_num', 'order_num'), ('study_plan', 'problem')},
        ),
        migrations.AddIndex(
            model_name='userstudyplan',
            index=models.Index(fields=['user', 'completed_at'], name='study_plans_user_id_a55be8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstudyplan',
            unique_together={('user', 'study_plan')},
        ),
        migrations.AddIndex(
            model_name='userstudyplanprogress',
            index=models.Index(fields=['user_study_plan', 'completed_at'], name='study_plans_user_st_e7b3d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstudyplanprogress',
            unique_together={('user_study_plan', 'study_plan_item')},
        ),
    ]
