# Generated by Django 5.2.4 on 2026-09-20 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_academicyear_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='colleges.college')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='colleges.academicsession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='colleges.section')),
                ('student_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assignments', to='colleges.collegemembership')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('college', 'name'), name='uniq_academicsession_name_per_college'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('college',), name='uniq_active_academicsession_per_college'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academicsession_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student_membership', 'academic_session'), name='uniq_active_assignment_per_student_session'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicassignment',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='studentassignment_left_not_before_joined'),
        ),
    ]
