# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('internal_error', 'Internal Error')], db_index=True, default='pending', max_length=30)),
                ('runtime_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('runtime_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memory_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('internal_error', 'Internal Error')], max_length=30)),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('runtime_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Submission Result',
            },
        ),
        migrations.CreateModel(
            name='UserSolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('first_solved_at', models.DateTimeField()),
                ('last_solved_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'User Solved Problem',
            },
        ),
        migrations.CreateModel(
            name='CodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('custom_input', models.TextField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('internal_error', 'Internal Error')], default='pending', max_length=30)),
                ('runtime_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_runs', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_runs', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Code Run',
                'ordering': ['-ran_at'],
            },
        ),
    ]
