# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coderun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='problems.language'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='problems.testcase'),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='best_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.language'),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_by', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='usersolvedproblem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coderun',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_9162dc_idx'),
        ),
        migrations.AddIndex(
            model_name='coderun',
            index=models.Index(fields=['user', 'ran_at'], name='submissions_user_id_f1cb03_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'status'], name='submissions_user_id_fb6f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='submissions_problem_a647ed_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'language', 'status'], name='submissions_problem_95f32f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresult',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_a2c1fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresult',
            unique_together={('submission', 'test_case')},
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['user'], name='submissions_user_id_4cbbec_idx'),
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['problem'], name='submissions_problem_3c954d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['user', 'first_solved_at'], name='submissions_user_id_1b0631_idx'),
        ),
        migrations.AddIndex(
            model_name='usersolvedproblem',
            index=models.Index(fields=['user', 'last_solved_at'], name='submissions_user_id_608647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersolvedproblem',
            unique_together={('user', 'problem')},
        ),
    ]
