# Generated by Django 5.2.4 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solve_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
