# Generated by Django 6.0.5 on 2026-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/attachments/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
    ]
