# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discussions', '0001_initial'),
        ('problems', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='problems.language'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion'),
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['problem', 'discussion_type'], name='discussions_problem_c9744a_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['problem', 'is_pinned', 'created_at'], name='discussions_problem_196b86_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['user', 'created_at'], name='discussions_user_id_46c8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['vote_count'], name='discussions_vote_co_a714e9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', 'parent', 'created_at'], name='discussions_discuss_7571bb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='discussions_user_id_2ed56e_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='discussions_content_7415a2_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='discussions_user_id_eb981b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
