# Generated by Django 5.2.4 on 2026-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount in smallest currency unit (paise, cents). Never store floats for money.')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, help_text='Stripe PaymentIntent ID (pi_xxxxx).', max_length=255, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, help_text='Stripe Invoice ID (in_xxxxx). Set for subscription renewal payments.', max_length=255)),
                ('failure_reason', models.TextField(blank=True, help_text='Populated from Stripe on failed charges. Empty on success.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete')], db_index=True, default='incomplete', max_length=20)),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='Stripe Subscription object ID (sub_xxxxx).', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe Customer object ID (cus_xxxxx).', max_length=255)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='True when the user has cancelled but the period has not expired yet.')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Set when status transitions to cancelled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.PositiveIntegerField(help_text='Price in smallest currency unit (e.g. paise, cents). 0 for free plans.')),
                ('price_yearly', models.PositiveIntegerField(help_text='Price in smallest currency unit for a full year.')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('features', models.JSONField(default=list, help_text='List of feature strings shown on the pricing page.')),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe Price ID for the monthly billing cycle.', max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, help_text='Stripe Price ID for the yearly billing cycle.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive plans are hidden from the pricing page but kept for historical FK integrity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ['price_monthly'],
            },
        ),
    ]
