# Generated by Django 5.2.4 on 2026-05-02 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('contest_type', models.CharField(choices=[('weekly', 'Weekly Contest'), ('biweekly', 'Biweekly Contest'), ('virtual', 'Virtual Contest'), ('special', 'Special Contest')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contest',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_minutes', models.PositiveIntegerField(default=0)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contest Participant',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Contest Problem',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='ContestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.PositiveIntegerField()),
                ('rating_after', models.PositiveIntegerField()),
                ('delta', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contest Rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_gained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_accepted', models.BooleanField(db_index=True, default=False)),
                ('penalty_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contest Submission',
            },
        ),
    ]
