# Generated by Django 5.2.4 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_appearances', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contestrating',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='contest_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestproblem'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='contests.contestparticipant'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time', 'is_published'], name='contests_co_start_t_308ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['contest_type', 'start_time'], name='contests_co_contest_2e37af_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipant',
            index=models.Index(fields=['contest', 'rank'], name='contests_co_contest_0420dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipant',
            index=models.Index(fields=['user', 'contest'], name='contests_co_user_id_47b230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipant',
            unique_together={('user', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'order_num'), ('contest', 'problem')},
        ),
        migrations.AddIndex(
            model_name='contestrating',
            index=models.Index(fields=['user', 'created_at'], name='contests_co_user_id_7b6299_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestrating',
            unique_together={('user', 'contest')},
        ),
        migrations.AddIndex(
            model_name='contestsubmission',
            index=models.Index(fields=['participant', 'contest_problem'], name='contests_co_partici_5fa0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contestsubmission',
            index=models.Index(fields=['participant', 'is_accepted'], name='contests_co_partici_16d607_idx'),
        ),
    ]
